# -*- coding: utf-8 -*-
"""COE 003 - NOV 11 2019

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZuI4AYTs7CRZP69SQiycdV_JFln6xSh
"""

bookmark_array = []
temporary_bookmarkarray = []

x = 0
while x == 0 :

  print("     --------")
  print("       MENU")
  print("     --------")
  print("  1) Add Bookmark")
  print("  2) Edit Bookmark")
  print("  3) Delete Bookmark")
  print("  4) View Bookmark")
  print("  5) Exit")

  input_number = int(input("\n Enter Number:"))

  if input_number == 1 :
      x_1 = 0
      print("\n\n\n\n\n\n\n\n\n\n")
      while x_1 == 0:
        add_bookmark = str(input("Enter link of Bookmark: "))
        bookmark_array.append(add_bookmark)

        exit_1 = str(input("Back to menu? (y/n): "))
        if exit_1 == "y" : 
          print("\n\n\n\n\n\n\n\n\n\n")
          break
        elif exit_1 == "n" :
          continue
      
  elif input_number == 2 :
      x_2 = 0
      print("\n\n\n\n\n\n\n\n\n\n")
      while x_2 == 0:
        n = 1
        for i in range (len(bookmark_array)):
          print(" ",n,".",bookmark_array[i])
          n = n + 1
        edit_number = int(input("Enter number to be edited: "))
        new_link = str(input("Enter new link: "))
        bookmark_array.insert(edit_number-1,new_link)
        bookmark_array.remove(bookmark_array[edit_number])
        
        exit_2 = str(input("Back to menu? (y/n): "))
        if exit_2 == "y" : 
          print("\n\n\n\n\n\n\n\n\n\n")
          break
        elif exit_2 == "n" :
          continue

  elif input_number == 3 :
      x_3 = 0
      print("\n\n\n\n\n\n\n\n\n\n")
      while x_3 == 0:
        n = 1
        for i in range (len(bookmark_array)):
          print(" ",n,".",bookmark_array[i])
          n = n + 1
        edit_number = int(input("Enter number to be edited: "))
        bookmark_array.pop(edit_number-1)

        exit_3 = str(input("Back to menu? (y/n): "))
        if exit_3 == "y" : 
          print("\n\n\n\n\n\n\n\n\n\n")
          break
        elif exit_3 == "n" :
          continue

  elif input_number == 4 :
      x_4 = 0
      print("\n\n\n\n\n\n\n\n\n\n")
      while x_4 == 0:
        n = 1
        for i in range (len(bookmark_array)):
          print(" ",n,".",bookmark_array[i])
          n = n + 1

        exit_4 = str(input("Back to menu? (y/n): "))
        if exit_4 == "y" : 
          print("\n\n\n\n\n\n\n\n\n\n")
          break
        elif exit_4 == "n" :
          continue

  elif input_number == 5 :
      break